### ISSUE TITLE
Import FHIR Ontology on Protege

### ISSUE THREAD

**Issue by hsolbrig** [BD2KOnFHIR/BLENDINGFHIRandRDF#6]
I'm looking to import the FHIR Ontology on Protege. I'm struggling to find out which is the right sequence of files to import .

I've replaced the content of the catalog-v001.xml with the content of catalog-remote.xml. Then I've tried to import the wrapper.owl in Protege 5.5 through Direct Import --> Import an ontology contained in a local file, but it gave me this errore:

ERROR 11:36:41 An error occurred whilst extracting the Ontology Id from the imported ontology: {}
java.lang.NullPointerException: null
at org.protege.editor.owl.model.repository.MasterOntologyIDExtractor.getOntologyId(MasterOntologyIDExtractor.java:27) ~[protege-editor-owl.jar:na]
at org.protege.editor.owl.ui.ontology.imports.wizard.page.AnticipateOntologyIdPage.checkImport(AnticipateOntologyIdPage.java:109) [protege-editor-owl.jar:na]
at org.protege.editor.owl.ui.ontology.imports.wizard.page.AnticipateOntologyIdPage.lambda$new$0(AnticipateOntologyIdPage.java:44) [protege-editor-owl.jar:na]
at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_121]
INFO 11:36:45 -------------------- Importing ontology and imports closure --------------------

**Comment by hsolbrig** [comment]
I just gave it a try on Mac OSX w/ Protege 5.5.0 "out of the box" and it works using the local fhir.ttl -- checking remote now.

Appears to work as well.   Can you check to see whether you can access http://build.fhir.org/fhir.ttl directly?

**Comment by Milena1530** [comment]
Using the ttl file you linked, I was able to import the ontology.
Thank you very much
